<?php

namespace Salex\MarketPlace\Models;

use Illuminate\Database\Eloquent\Model;
use Salex\MarketPlace\Contracts\Seller as SellerContract;
use Webkul\Customer\Models\Customer;

class Seller extends Customer implements SellerContract
{
    protected $table = 'customers';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(function ($query){
            $query->whereNotNull('store_id');
        });

    }

}